### ISSUE TITLE
根据i386手册，pop的时候esp不应该是+4吗，测试用例里面写的是-4

### ISSUE THREAD

**Issue by pppppkun** [COA-2019/programming-answer#4]
![image](https://user-images.githubusercontent.com/43557766/70141119-46cc6e00-16d1-11ea-84c7-9fef550db4fd.png)

**Comment by fraliphsoft** [comment]
hi~这个是push，测试用例假装push了一个数据，esp-4，然后下面开始测试pop
虽然我也不知道为什么这里不直接write(全0)而是write了两次，可能写这个用例的助教当时想表明已经假装push了一个数据进去吧233



546773427@qq.com
 
发件人： pppppkun
发送时间： 2019-12-04 20:04
收件人： COA-2019/programming-answer
抄送： Subscribed
主题： [COA-2019/programming-answer] 根据i386手册，pop的时候esp不应该是+4吗，测试用例里面写的是-4 (#4)

**Comment by pppppkun** [comment]
> hi~这个是push，测试用例假装push了一个数据，esp-4，然后下面开始测试pop 虽然我也不知道为什么这里不直接write(全0)而是write了两次，可能写这个用例的助教当时想表明已经假装push了一个数据进去吧233 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-04 20:04 收件人： COA-2019/programming-answer 抄送： Subscribed 主题： [COA-2019/programming-answer] 根据i386手册，pop的时候esp不应该是+4吗，测试用例里面写的是-4 (#4) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

看漏了下面的push，眼拙了
另外想问问有没有什么方法可以让java也像PA里面那样使用宏定义

**Comment by fraliphsoft** [comment]
其实有很多种方式可以模拟，但我猜都不是你想要的。。。Java在设计之初就认为宏是不好的，所以ban掉了，他没有那种编译时就替换的高性能宏操作

如果想模拟的话，可以考虑专门建立一个类存放static final常量，其他方法都会很复杂，比如：
1. Java反射机制
2. AOP面向切面编程(其实本质也是反射)
3. 直接修改.class字节码文件，比如JavaAssist工具库



546773427@qq.com
 
发件人： pppppkun
发送时间： 2019-12-04 20:34
收件人： COA-2019/programming-answer
抄送： fraliphsoft; Comment
主题： Re: [COA-2019/programming-answer] 根据i386手册，pop的时候esp不应该是+4吗，测试用例里面写的是-4 (#4)
hi~这个是push，测试用例假装push了一个数据，esp-4，然后下面开始测试pop 虽然我也不知道为什么这里不直接write(全0)而是write了两次，可能写这个用例的助教当时想表明已经假装push了一个数据进去吧233 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-04 20:04 收件人： COA-2019/programming-answer 抄送： Subscribed 主题： [COA-2019/programming-answer] 根据i386手册，pop的时候esp不应该是+4吗，测试用例里面写的是-4 (#4) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
看漏了下面的push，眼拙了
另外想问问有没有什么方法可以让java也像PA里面那样使用宏定义

**Comment by pppppkun** [comment]
其实我觉得可以用反射可以基本模拟pa那样的效果，然后再经过一些设计看起来应该就比较美观了------------------ 原始邮件 ------------------
发件人: "fraliphsoft"<notifications@github.com>
发送时间: 2019年12月4日(星期三) 晚上8:40
收件人: "COA-2019/programming-answer"<programming-answer@noreply.github.com>;
抄送: "pppppkun"<936637810@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [COA-2019/programming-answer] 根据i386手册，pop的时候esp不应该是+4吗，测试用例里面写的是-4 (#4)


其实有很多种方式可以模拟，但我猜都不是你想要的。。。Java在设计之初就认为宏是不好的，所以ban掉了，他没有那种编译时就替换的高性能宏操作 
 
 如果想模拟的话，可以考虑专门建立一个类存放static final常量，其他方法都会很复杂，比如： 
 1. Java反射机制 
 2. AOP面向切面编程(其实本质也是反射) 
 3. 直接修改.class字节码文&#x4EF6;，比如JavaAssist工具库 
 
 
 
 546773427@qq.com 
   
 发&#x4EF6;人： pppppkun 
 发送时间： 2019-12-04 20:34 
 收&#x4EF6;人： COA-2019/programming-answer 
 抄送： fraliphsoft; Comment 
 主题： Re: [COA-2019/programming-answer] 根据i386手册，pop的时候esp不应该是+4吗，测试用例里面写的是-4 (#4) 
 hi~这个是push，测试用例假装push了一个数据，esp-4，然后下面开始测试pop 虽然我也不知道为什么这里不直接write(全0)而是write了两次，可能写这个用例的助教当时想表明已经假装push了一个数据进去吧233 546773427@qq.com 发&#x4EF6;人： pppppkun 发送时间： 2019-12-04 20:04 收&#x4EF6;人： COA-2019/programming-answer 抄送： Subscribed 主题： [COA-2019/programming-answer] 根据i386手册，pop的时候esp不应该是+4吗，测试用例里面写的是-4 (#4) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 
 看漏了下面的push，眼拙了 
 另外想问问有没有什么方法可以让java也像PA里面那样使用宏定义 
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
&mdash;
