### ISSUE TITLE
请问第七个用例是什么肥事啊

### ISSUE THREAD

**Issue by pppppkun** [COA-2019/programming-answer#6]
![image](https://user-images.githubusercontent.com/43557766/70541675-70d6d200-1ba2-11ea-8b74-3b60af06a5ff.png)
按道理ZF不是只有运算结果为0的时候才是True，其余时候都是false吗，为什么用例里面是assertTrue，然后最后加了三次为啥eax里面还是全0啊

**Comment by pppppkun** [comment]
而且i386手册里面cmp不是不存result吗，为啥我们也存了

**Comment by fraliphsoft** [comment]
546773427@qq.com
 
发件人： pppppkun
发送时间： 2019-12-10 23:23
收件人： COA-2019/programming-answer
抄送： Subscribed
主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6)
而且i386手册里面cmp不是不存result吗，为啥我们也存了

**Comment by pppppkun** [comment]
> 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-10 23:23 收件人： COA-2019/programming-answer 抄送： Subscribed 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) 而且i386手册里面cmp不是不存result吗，为啥我们也存了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

?

**Comment by fraliphsoft** [comment]
cmp是不存result，我不是很清楚“我们也存了”的结论是怎么的出来的。。。不过cmp会修改ZF，根据i386手册，cmp的实现应该是,如果减的结果为0，ZF应该会被置为0，JZ生效；

不过刚刚又有同学反应JZ的8-bits操作数应该是offset而不直接是eip值，这个是对的，我们上个版本的实现是offset，后来更新ICC的时候没pull导致覆盖成了错误代码(目标助教已被消灭).......已经在调整，请等候任老师通知(Moodle)



546773427@qq.com
 
发件人： pppppkun
发送时间： 2019-12-11 00:03
收件人： COA-2019/programming-answer
抄送： fraliphsoft; Comment
主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6)
546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-10 23:23 收件人： COA-2019/programming-answer 抄送： Subscribed 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) 而且i386手册里面cmp不是不存result吗，为啥我们也存了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
?

**Comment by pppppkun** [comment]
> cmp是不存result，我不是很清楚“我们也存了”的结论是怎么的出来的。。。不过cmp会修改ZF，根据i386手册，cmp的实现应该是,如果减的结果为0，ZF应该会被置为0，JZ生效； 不过刚刚又有同学反应JZ的8-bits操作数应该是offset而不直接是eip值，这个是对的，我们上个版本的实现是offset，后来更新ICC的时候没pull导致覆盖成了错误代码(目标助教已被消灭).......已经在调整，请等候任老师通知(Moodle) 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-11 00:03 收件人： COA-2019/programming-answer 抄送： fraliphsoft; Comment 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-10 23:23 收件人： COA-2019/programming-answer 抄送： Subscribed 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) 而且i386手册里面cmp不是不存result吗，为啥我们也存了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. ? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/43557766/70583533-fa18f380-1bf8-11ea-9246-30c1921db5c4.png)
就是上次cmp检查了eax里面的值，我说的关于第七个用例的问题也是按照手册第七个用例的执行顺序应该是最开始那个图，但是测试用例里面好像是JZ跳转往后马上就HLT了

**Comment by fraliphsoft** [comment]
看了下cmp确实存了eax。。打死的助教又多了一只，考虑到“是否写eax”对当前用例影响不大，可以先按照写eax的方法实现(面向用例编程√)，另外我刚刚改了下file_test7的用例，目前正在试图联系任老师ing，请耐心等候，修改后的用例为：

0000010100000001100000101101001001010100
0011110100000001100000101101001001010100
0111010001011000
0000010100000001100000101101001001010100
0000010100000001100000101101001001010100
11110100



546773427@qq.com
 
发件人： pppppkun
发送时间： 2019-12-11 09:33
收件人： COA-2019/programming-answer
抄送： fraliphsoft; Comment
主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6)
cmp是不存result，我不是很清楚“我们也存了”的结论是怎么的出来的。。。不过cmp会修改ZF，根据i386手册，cmp的实现应该是,如果减的结果为0，ZF应该会被置为0，JZ生效； 不过刚刚又有同学反应JZ的8-bits操作数应该是offset而不直接是eip值，这个是对的，我们上个版本的实现是offset，后来更新ICC的时候没pull导致覆盖成了错误代码(目标助教已被消灭).......已经在调整，请等候任老师通知(Moodle) 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-11 00:03 收件人： COA-2019/programming-answer 抄送： fraliphsoft; Comment 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-10 23:23 收件人： COA-2019/programming-answer 抄送： Subscribed 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) 而且i386手册里面cmp不是不存result吗，为啥我们也存了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. ? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

就是上次cmp检查了eax里面的值，我说的关于第七个用例的问题也是按照手册第七个用例的执行顺序应该是最开始那个图，但是测试用例里面好像是JZ跳转往后马上就HLT了

**Comment by pppppkun** [comment]
> 看了下cmp确实存了eax。。打死的助教又多了一只，考虑到“是否写eax”对当前用例影响不大，可以先按照写eax的方法实现(面向用例编程√)，另外我刚刚改了下file_test7的用例，目前正在试图联系任老师ing，请耐心等候，修改后的用例为： 0000010100000001100000101101001001010100 0011110100000001100000101101001001010100 0111010001011000 0000010100000001100000101101001001010100 0000010100000001100000101101001001010100 11110100 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-11 09:33 收件人： COA-2019/programming-answer 抄送： fraliphsoft; Comment 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) cmp是不存result，我不是很清楚“我们也存了”的结论是怎么的出来的。。。不过cmp会修改ZF，根据i386手册，cmp的实现应该是,如果减的结果为0，ZF应该会被置为0，JZ生效； 不过刚刚又有同学反应JZ的8-bits操作数应该是offset而不直接是eip值，这个是对的，我们上个版本的实现是offset，后来更新ICC的时候没pull导致覆盖成了错误代码(目标助教已被消灭).......已经在调整，请等候任老师通知(Moodle) 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-11 00:03 收件人： COA-2019/programming-answer 抄送： fraliphsoft; Comment 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-10 23:23 收件人： COA-2019/programming-answer 抄送： Subscribed 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) 而且i386手册里面cmp不是不存result吗，为啥我们也存了 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. ? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 就是上次cmp检查了eax里面的值，我说的关于第七个用例的问题也是按照手册第七个用例的执行顺序应该是最开始那个图，但是测试用例里面好像是JZ跳转往后马上就HLT了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

请问如果想加入到课程建设中该如何加入呀！

**Comment by fraliphsoft** [comment]
你可以找任老师聊聊，不过建议想好，你们大三估计会比较忙。



546773427@qq.com
 
发件人： pppppkun
发送时间： 2019-12-11 14:02
收件人： COA-2019/programming-answer
抄送： fraliphsoft; Comment
主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6)
看了下cmp确实存了eax。。打死的助教又多了一只，考虑到“是否写eax”对当前用例影响不大，可以先按照写eax的方法实现(面向用例编程√)，另外我刚刚改了下file_test7的用例，目前正在试图联系任老师ing，请耐心等候，修改后的用例为： 0000010100000001100000101101001001010100 0011110100000001100000101101001001010100 0111010001011000 0000010100000001100000101101001001010100 0000010100000001100000101101001001010100 11110100 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-11 09:33 收件人： COA-2019/programming-answer 抄送： fraliphsoft; Comment 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) cmp是不存result，我不是很清楚“我们也存了”的结论是怎么的出来的。。。不过cmp会修改ZF，根据i386手册，cmp的实现应该是,如果减的结果为0，ZF应该会被置为0，JZ生效； 不过刚刚又有同学反应JZ的8-bits操作数应该是offset而不直接是eip值，这个是对的，我们上个版本的实现是offset，后来更新ICC的时候没pull导致覆盖成了错误代码(目标助教已被消灭).......已经在调整，请等候任老师通知(Moodle) 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-11 00:03 收件人： COA-2019/programming-answer 抄送： fraliphsoft; Comment 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) 546773427@qq.com 发件人： pppppkun 发送时间： 2019-12-10 23:23 收件人： COA-2019/programming-answer 抄送： Subscribed 主题： Re: [COA-2019/programming-answer] 请问第七个用例是什么肥事啊 (#6) 而且i386手册里面cmp不是不存result吗，为啥我们也存了 ― You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. ? ― You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 就是上次cmp检查了eax里面的值，我说的关于第七个用例的问题也是按照手册第七个用例的执行顺序应该是最开始那个图，但是测试用例里面好像是JZ跳转往后马上就HLT了 ― You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
请问如果想加入到课程建设中该如何加入呀！
―
